### PR TITLE
Notebook Creation

### PR DESCRIPTION
**Pull request by nkorinek**
Adding content to the notebooks

### CODE REVIEW

**Comment by nkorinek** [comment]
@lwasser maybe take a look at this (when you're back) and see if we're on track. I can flesh out the blog to make it a little more interesting, but it seems that it works for me! One caviate: the bash script only runs if it's in the earth-analytics-python conda environment, since it needs nbextensions to run. Should I add something to the bash script to install all needed packages?

**Comment by lwasser** [comment]
@nkorinek this is great. How about you add a readme file that has a nice introduction to this repo and then installation instructions that include a link to the ea-python envt as part of the installation instructions. Or better yet, you could include an envt file with just the packages needed to run this repo and instructions to install in the readme. either work for me but i might lean towards a custom envt with just the things that the use needs..

**Comment by nkorinek** [comment]
@lwasser updated!

**Comment by nkorinek** [comment]
One thing I thought about is that we COULD add in the environment creation steps into the bash script, but that may be overcomplicating things. Just a thought!

**Comment by lwasser** [comment]
@nkorinek i  am not sure  that is ideal because the envt gets setup and activated once. you'd have to implement a check. I think  we  just go with  the  normal  OSS workflow of  setup the envt and then run via bash or Make  potentially. i love that idea however!! 

thank you so much for this - i'll look at it either   later today or tomorrow first  thing!

**Pull request merged**
